set_xmakever("3.1.1")
set_project("CSim")
set_version("0.0.1")
set_languages("cxx17")
add_rules("mode.debug", "mode.release")

-- All current dependencies are local system packages; skip repository updates.
set_policy("network.mode", "private")

option("viewer")
    set_default(false)
    set_showmenu(true)
    set_description("Build the OpenGL/GLFW viewer")
option_end()

option("python")
    set_default(false)
    set_showmenu(true)
    set_description("Build the pybind11 Python module")
option_end()

option("python_executable")
    set_default("python3")
    set_showmenu(true)
    set_description("Python interpreter used to build and run the bindings")
option_end()

-- The numerics library provides linear algebra and rotation operations.
target("csim_numerics")
    set_kind("headeronly")
    add_headerfiles("include/(csim/math/*.hpp)", "include/(csim/numerics/*.hpp)")
    add_includedirs("include", {public = true})
target_end()

-- Description data stays independent of XML; implementations are in csim_io.
target("csim_model")
    set_kind("headeronly")
    add_headerfiles("include/(csim/model/*.hpp)", "include/(csim/io/*.hpp)")
    add_includedirs("include", {public = true})
    add_deps("csim_numerics")
target_end()

target("csim_dynamics")
    set_kind("headeronly")
    add_headerfiles("include/(csim/dynamics/*.hpp)")
    add_deps("csim_numerics")
target_end()

add_requires("pkgconfig::tinyxml2", {alias = "tinyxml2", system = true})
target("csim_io")
    set_kind("static")
    set_policy("build.fence", true)
    add_files("src/io/*.cpp", "src/model/*.cpp")
    add_deps("csim_model", "csim_dynamics")
    add_packages("tinyxml2", {public = true})
    if is_plat("linux") then add_cxflags("-fPIC") end
target_end()

target("csim_simulation")
    set_kind("headeronly")
    add_headerfiles("include/(csim/simulation/*.hpp)")
    add_deps("csim_dynamics", "csim_model")
target_end()

target("simulator")
    set_kind("binary")
    add_files("apps/simulator/main.cpp")
    add_deps("csim_simulation")
target_end()

target("vector_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/math/vector_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("matrix_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/math/matrix_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("lu_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/math/lu_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("decompositions_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/math/decompositions_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("rotation_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/math/rotation_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("rk4_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/numerics/rk4_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("dormand_prince_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/numerics/dormand_prince_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("pendulum_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/dynamics/pendulum_test.cpp")
    add_deps("csim_dynamics", "csim_model")
    add_tests("default")
target_end()

target("pendulum_simulation_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/pendulum_test.cpp")
    add_deps("csim_simulation")
    add_tests("default")
target_end()

target("drone_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/dynamics/drone_test.cpp")
    add_deps("csim_dynamics", "csim_model")
    add_tests("default")
target_end()

target("drone_simulation_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/drone_test.cpp")
    add_deps("csim_simulation")
    add_tests("default")
target_end()

target("suspended_payload_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/dynamics/suspended_payload_test.cpp")
    add_deps("csim_dynamics", "csim_model")
    add_tests("default")
target_end()

target("suspended_payload_simulation_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/suspended_payload_test.cpp")
    add_deps("csim_simulation")
    add_tests("default")
target_end()

-- Camera, playback and CSV checks stay available without graphics dependencies.
target("viewer_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/viewer/viewer_test.cpp", "apps/viewer/camera.cpp",
              "apps/viewer/scene.cpp", "apps/viewer/trajectory.cpp")
    add_includedirs("apps/viewer")
    add_deps("csim_simulation")
    add_tests("default")
target_end()

if has_config("viewer") then
    includes("apps/viewer/xmake.lua")
end

if has_config("python") then
    includes("bindings/python/xmake.lua")
end

target("explicit_methods_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/numerics/explicit_methods_test.cpp")
    add_deps("csim_numerics")
    add_tests("default")
target_end()

target("cable_events_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/cable_events_test.cpp")
    add_deps("csim_simulation")
    add_tests("default")
target_end()

target("drone_batch_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/drone_batch_test.cpp")
    add_deps("csim_simulation")
    if is_plat("linux") then add_syslinks("pthread") end
    add_tests("default")
target_end()

target("rigid_payload_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/rigid_payload_test.cpp")
    add_deps("csim_simulation")
    add_tests("default")
target_end()

target("rigid_payload_batch_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/simulation/rigid_payload_batch_test.cpp")
    add_deps("csim_simulation")
    if is_plat("linux") then add_syslinks("pthread") end
    add_tests("default")
target_end()

target("advanced_methods_test")
    set_kind("binary")
    set_default(false)
    add_files("tests/numerics/advanced_methods_test.cpp")
    add_deps("csim_simulation")
    add_tests("default")
target_end()
